version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
        - 1883:1883

  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:stable
    volumes:
      - /home/pi/homeassistant:/config
    environment:
      - TZ=Africa/Johannesburg
    restart: always
    network_mode: host

  voltronic-mqtt:

    image: bushrangers/ha-voltronic-mqtt

    # Uncomment if you want to build your own local version.
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev


    container_name: voltronic-mqtt

    privileged: true
    restart: always

    volumes:
        - ./config/:/etc/inverter/
        - ./sources/:/opt/
    devices:
    #  - "/dev/mem:/dev/mem"

    # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm

    # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2

      - /dev/hidraw0:/dev/hidraw0

  # Used to auto-update images as we release new versions...
  watchtower:
    # Please see the following for configuration options:
    #    https://containrrr.github.io/watchtower/container-selection/
    image: containrrr/watchtower
    container_name: watchtower

    restart: always
    privileged: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 500
